# Auto-generated by genxls. DO NOT EDIT.
extends Resource
class_name CQuest

@export var cid: int
@export var count: int
@export var data: String
@export var dt: Array[int] = []
@export var dt_arr: Array = []
