# Code generated by genpb. DO NOT EDIT.

const CmdReq = preload("cmd_req.gd")
const CmdRsp = preload("cmd_rsp.gd")
const CmdDsp = preload("cmd_dsp.gd")
const Cmd    = preload("cmd.gd")

var _factories: Dictionary = {}
var _key_names: Dictionary = {}

func _init():
	_factories[Cmd.EKey.T.ReqLogin] = func(): return CmdReq.ReqLogin.new()
	_factories[Cmd.EKey.T.ReqCreateRole] = func(): return CmdReq.ReqCreateRole.new()
	_factories[Cmd.EKey.T.ReqLoginRole] = func(): return CmdReq.ReqLoginRole.new()
	_factories[Cmd.EKey.T.ReqPing] = func(): return CmdReq.ReqPing.new()
	_factories[Cmd.EKey.T.ReqPingZZZ] = func(): return CmdReq.ReqPingZZZ.new()
	_factories[Cmd.EKey.T.ReqEnterZone] = func(): return CmdReq.ReqEnterZone.new()
	_factories[Cmd.EKey.T.ReqMove] = func(): return CmdReq.ReqMove.new()
	_factories[Cmd.EKey.T.RspLogin] = func(): return CmdRsp.RspLogin.new()
	_factories[Cmd.EKey.T.RspCreateRole] = func(): return CmdRsp.RspCreateRole.new()
	_factories[Cmd.EKey.T.RspLoginRole] = func(): return CmdRsp.RspLoginRole.new()
	_factories[Cmd.EKey.T.RspPing] = func(): return CmdRsp.RspPing.new()
	_factories[Cmd.EKey.T.RspPingZZZ] = func(): return CmdRsp.RspPingZZZ.new()
	_factories[Cmd.EKey.T.RspEnterZone] = func(): return CmdRsp.RspEnterZone.new()
	_factories[Cmd.EKey.T.RspMove] = func(): return CmdRsp.RspMove.new()
	_factories[Cmd.EKey.T.DspLogin] = func(): return CmdDsp.DspLogin.new()
	_factories[Cmd.EKey.T.DspSrvMaintain] = func(): return CmdDsp.DspSrvMaintain.new()
	_factories[Cmd.EKey.T.DspKickRole] = func(): return CmdDsp.DspKickRole.new()
	_factories[Cmd.EKey.T.DspEnterZone] = func(): return CmdDsp.DspEnterZone.new()
	_factories[Cmd.EKey.T.DspMove] = func(): return CmdDsp.DspMove.new()
	_key_names[Cmd.EKey.T.ReqLogin] = "req_login"
	_key_names[Cmd.EKey.T.ReqCreateRole] = "req_create_role"
	_key_names[Cmd.EKey.T.ReqLoginRole] = "req_login_role"
	_key_names[Cmd.EKey.T.ReqPing] = "req_ping"
	_key_names[Cmd.EKey.T.ReqPingZZZ] = "req_ping_zzz"
	_key_names[Cmd.EKey.T.ReqEnterZone] = "req_enter_zone"
	_key_names[Cmd.EKey.T.ReqMove] = "req_move"
	_key_names[Cmd.EKey.T.RspLogin] = "rsp_login"
	_key_names[Cmd.EKey.T.RspCreateRole] = "rsp_create_role"
	_key_names[Cmd.EKey.T.RspLoginRole] = "rsp_login_role"
	_key_names[Cmd.EKey.T.RspPing] = "rsp_ping"
	_key_names[Cmd.EKey.T.RspPingZZZ] = "rsp_ping_zzz"
	_key_names[Cmd.EKey.T.RspEnterZone] = "rsp_enter_zone"
	_key_names[Cmd.EKey.T.RspMove] = "rsp_move"
	_key_names[Cmd.EKey.T.DspLogin] = "dsp_login"
	_key_names[Cmd.EKey.T.DspSrvMaintain] = "dsp_srv_maintain"
	_key_names[Cmd.EKey.T.DspKickRole] = "dsp_kick_role"
	_key_names[Cmd.EKey.T.DspEnterZone] = "dsp_enter_zone"
	_key_names[Cmd.EKey.T.DspMove] = "dsp_move"


func new_msg(key: int):
	if _factories.has(key):
		return _factories[key].call()
	return null


func unmarshal(key: int, body: PackedByteArray):
	var msg = new_msg(key)
	if msg == null:
		return null
	var err = msg.from_bytes(body)
	if err != Cmd.PB_ERR.NO_ERRORS:
		return null
	return msg


func key_name(key: int) -> String:
	return _key_names.get(key, "")


static func marshal_request(key: int, msg) -> PackedByteArray:
	var body: PackedByteArray = msg.to_bytes()
	var buf := PackedByteArray()
	buf.resize(6 + body.size())
	buf.encode_u16(0, key)
	buf.encode_u32(2, body.size())
	for i in body.size():
		buf[6 + i] = body[i]
	return buf
