use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use heck::ToUpperCamelCase;
use regex::Regex;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let proto_dir = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("..")
        .join("comm")
        .join("tools")
        .join("genpb")
        .join("proto");

    let proto_dir = proto_dir
        .canonicalize()
        .expect("proto directory not found – expected at comm/tools/genpb/proto");

    let exclude = ["data_srv.proto", "data_fwd.proto"];
    let proto_files: Vec<PathBuf> = fs::read_dir(&proto_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension().map_or(false, |ext| ext == "proto")
                && !exclude.contains(&p.file_name().unwrap().to_str().unwrap())
        })
        .collect();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let proto_strs: Vec<&str> = proto_files
        .iter()
        .map(|p| p.to_str().expect("non-utf8 proto path"))
        .collect();
    let file_descriptor_set =
        protox::compile(proto_strs, [proto_dir.to_str().unwrap()])
            .expect("protox failed to compile proto files");

    prost_build::Config::new()
        .out_dir(&out_dir)
        .compile_fds(file_descriptor_set)
        .expect("Failed to generate Rust code from proto files");

    generate_cmd_ext(&proto_dir, &out_dir);

    println!("cargo:rerun-if-changed={}", proto_dir.display());
    for f in &proto_files {
        println!("cargo:rerun-if-changed={}", f.display());
    }
}

struct EKeyEntry {
    name: String,
    value: u32,
}

/// Convert a proto name to the Rust type name prost generates (UpperCamelCase).
fn prost_name(proto: &str) -> String {
    proto.to_upper_camel_case()
}

fn generate_cmd_ext(proto_dir: &Path, out_dir: &Path) {
    let cmd_content = fs::read_to_string(proto_dir.join("cmd.proto")).unwrap();
    let ekey_re = Regex::new(r"(\w+)\s*=\s*(\d+)\s*;").unwrap();

    let mut ekeys: Vec<EKeyEntry> = Vec::new();
    for cap in ekey_re.captures_iter(&cmd_content) {
        let name = cap[1].to_string();
        let value: u32 = cap[2].parse().unwrap();
        if value == 0 || value == 65535 {
            continue;
        }
        ekeys.push(EKeyEntry { name, value });
    }
    ekeys.sort_by_key(|e| e.value);

    let msg_re = Regex::new(r"message\s+(\w+)\s*\{").unwrap();
    let req_msgs = parse_messages(proto_dir, "cmd_req.proto", &msg_re);
    let rsp_msgs = parse_messages(proto_dir, "cmd_rsp.proto", &msg_re);
    let dsp_msgs = parse_messages(proto_dir, "cmd_dsp.proto", &msg_re);

    let mut code = String::with_capacity(8192);

    code.push_str("// Code generated by netcore build.rs – DO NOT EDIT.\n\n");
    code.push_str("use prost::Message;\n\n");

    // ── EKey enum (use prost-normalized names) ──
    code.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n");
    code.push_str("#[repr(u16)]\n");
    code.push_str("pub enum EKey {\n");
    for e in &ekeys {
        code.push_str(&format!("    {} = {},\n", prost_name(&e.name), e.value));
    }
    code.push_str("}\n\n");

    // ── EKey::from_u16 / as_u16 ──
    code.push_str("impl EKey {\n");
    code.push_str("    pub fn from_u16(v: u16) -> Option<EKey> {\n");
    code.push_str("        match v {\n");
    for e in &ekeys {
        code.push_str(&format!(
            "            {} => Some(EKey::{}),\n",
            e.value,
            prost_name(&e.name)
        ));
    }
    code.push_str("            _ => None,\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");
    code.push_str("    pub fn as_u16(self) -> u16 {\n");
    code.push_str("        self as u16\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // ── ServerMessage enum (Rsp + Dsp) ──
    code.push_str("#[derive(Clone, Debug)]\n");
    code.push_str("pub enum ServerMessage {\n");
    for msg in rsp_msgs.iter().chain(dsp_msgs.iter()) {
        let rn = prost_name(msg);
        code.push_str(&format!("    {}(crate::pb::{}),\n", rn, rn));
    }
    code.push_str("}\n\n");

    // ── ClientMessage enum (Req) ──
    code.push_str("#[derive(Clone, Debug)]\n");
    code.push_str("pub enum ClientMessage {\n");
    for msg in &req_msgs {
        let rn = prost_name(msg);
        code.push_str(&format!("    {}(crate::pb::{}),\n", rn, rn));
    }
    code.push_str("}\n\n");

    // ── encode_client_message ──
    code.push_str("pub fn encode_client_message(msg: &ClientMessage) -> (EKey, Vec<u8>) {\n");
    code.push_str("    match msg {\n");
    for msg in &req_msgs {
        if let Some(ek_proto) = find_ekey(&ekeys, msg) {
            let rn = prost_name(msg);
            let ek = prost_name(&ek_proto);
            code.push_str(&format!(
                "        ClientMessage::{}(inner) => (EKey::{}, inner.encode_to_vec()),\n",
                rn, ek
            ));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // ── decode_server_message ──
    code.push_str(
        "pub fn decode_server_message(key: EKey, data: &[u8]) -> Result<ServerMessage, prost::DecodeError> {\n",
    );
    code.push_str("    match key {\n");
    for msg in rsp_msgs.iter().chain(dsp_msgs.iter()) {
        if let Some(ek_proto) = find_ekey(&ekeys, msg) {
            let rn = prost_name(msg);
            let ek = prost_name(&ek_proto);
            code.push_str(&format!(
                "        EKey::{} => Ok(ServerMessage::{}(crate::pb::{}::decode(data)?)),\n",
                ek, rn, rn
            ));
        }
    }
    code.push_str(
        "        _ => Err(prost::DecodeError::new(format!(\"no decoder for key {:?}\", key))),\n",
    );
    code.push_str("    }\n");
    code.push_str("}\n");

    let path = out_dir.join("cmd_ext.rs");
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(code.as_bytes()).unwrap();
    println!("cargo:warning=Generated {}", path.display());
}

fn parse_messages(proto_dir: &Path, filename: &str, re: &Regex) -> Vec<String> {
    let content = fs::read_to_string(proto_dir.join(filename)).unwrap();
    re.captures_iter(&content)
        .map(|cap| cap[1].to_string())
        .collect()
}

/// Find the EKey entry matching a message name (using proto names, before normalization).
fn find_ekey(ekeys: &[EKeyEntry], msg_name: &str) -> Option<String> {
    if let Some(e) = ekeys.iter().find(|e| e.name == msg_name) {
        return Some(e.name.clone());
    }
    let prefixes = ["Req", "Rsp", "Dsp"];
    for prefix in &prefixes {
        if !msg_name.starts_with(prefix) {
            continue;
        }
        let msg_suffix = &msg_name[prefix.len()..];
        for e in ekeys {
            if !e.name.starts_with(prefix) {
                continue;
            }
            let ek_suffix = &e.name[prefix.len()..];
            if msg_suffix.ends_with(ek_suffix) || ek_suffix.ends_with(msg_suffix) {
                return Some(e.name.clone());
            }
        }
    }
    None
}
