# Auto-generated by genxls. DO NOT EDIT.
extends SceneTree

const JSON_PATH = "res://data/config/all.json"
const OUT_DIR = "res://data/generated/"

func _to_int_array(arr) -> Array[int]:
	var result: Array[int] = []
	if arr is Array:
		for v in arr:
			result.append(int(v))
	return result

func _to_int_array_2d(arr) -> Array:
	var result: Array = []
	if arr is Array:
		for sub in arr:
			result.append(_to_int_array(sub))
	return result

func _init():
	var file = FileAccess.open(JSON_PATH, FileAccess.READ)
	if file == null:
		printerr("Failed to open: ", JSON_PATH)
		quit(1)
		return
	var text = file.get_as_text()
	file.close()
	var data = JSON.parse_string(text)
	if data == null:
		printerr("Failed to parse JSON")
		quit(1)
		return

	DirAccess.make_dir_recursive_absolute(OUT_DIR)
	var config = CAllConfig.new()

	# --- Item ---
	var items_container = CItems.new()
	for entry in data.get("items", []):
		var item = CItem.new()
		item.cid = int(entry.get("cid", 0))
		item.count = int(entry.get("count", 0))
		item.data = str(entry.get("data", ""))
		item.dt = _to_int_array(entry.get("dt", []))
		item.dt_arr = _to_int_array_2d(entry.get("dtArr", []))
		items_container.items.append(item)
		config.items.append(item)
	ResourceSaver.save(items_container, OUT_DIR + "items.res")
	print("  saved: items.res")

	# --- Quest ---
	var quests_container = CQuests.new()
	for entry in data.get("quests", []):
		var item = CQuest.new()
		item.cid = int(entry.get("cid", 0))
		item.count = int(entry.get("count", 0))
		item.data = str(entry.get("data", ""))
		item.dt = _to_int_array(entry.get("dt", []))
		item.dt_arr = _to_int_array_2d(entry.get("dtArr", []))
		quests_container.items.append(item)
		config.quests.append(item)
	ResourceSaver.save(quests_container, OUT_DIR + "quests.res")
	print("  saved: quests.res")

	ResourceSaver.save(config, OUT_DIR + "game_config.res")
	print("saved: game_config.res (2 tables)")
	quit()
